import { describe, it, expect } from 'vitest'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

const source = name => readFileSync(resolve(process.cwd(), 'src', name), 'utf8')

describe('mobile accessibility and layout contracts', () => {
  it('keeps shared controls and navigation semantic', () => {
    const ui = source('components/ui.jsx')
    const tabs = source('components/TabBar.jsx')
    const workout = source('views/Workout.jsx')
    expect(ui).toContain('role="switch"')
    expect(ui).toContain('role="checkbox"')
    expect(ui).toContain('role="slider"')
    expect(ui).toContain('aria-pressed={o.value === value}')
    expect(tabs).toContain('aria-current={on(k) ? \'page\' : undefined}')
    expect(workout).toContain('aria-label={t(\'Sets\')')
  })

  it('keeps narrow controls and fixed navigation clear of content', () => {
    const css = source('index.css')
    const home = source('views/Home.jsx')
    expect(css).toContain('flex-wrap:wrap')
    expect(css).toContain('min-height:44px')
    expect(css).toContain('calc(180px + var(--sab))')
    expect(css).toContain('bottom:calc(96px + var(--sab))')
    expect(css).toContain('.calendar-nav{padding-inline:44px}')
    expect(home).toContain('style={{ width: 44, height: 44, fontSize: 15 }}')
  })

  it('keeps exercise and workout note boxes independently discoverable and collapsible', () => {
    const sheets = source('sheets.jsx')
    const workout = source('views/Workout.jsx')
    expect(sheets).toContain("t('Exercise note')")
    expect(sheets).not.toContain("t('Trainer note')")
    expect(sheets).toContain('const [planNoteOpen, setPlanNoteOpen] = useState(true)')
    expect(sheets).toContain('aria-expanded={planNoteOpen}')
    expect(sheets).toContain('aria-controls="exercise-plan-note-content"')
    expect(sheets).toContain('<div id="exercise-plan-note-content" hidden={!planNoteOpen}>')
    expect(sheets).toContain("<Icon name={planNoteOpen ? 'chevronUp' : 'chevronDown'} />")
    expect(sheets).toContain('id="exercise-plan-note"')
    expect(workout).toContain("t('Exercise note')")
    expect(workout).not.toContain("t('Trainer note')")
    expect(workout).toContain("const [workoutNoteOpen, setWorkoutNoteOpen] = useState(() => typeof entry.note === 'string' && entry.note.trim().length > 0)")
    expect(workout).toContain("entry.note.trim().length > 0")
    expect(workout).toContain('aria-expanded={workoutNoteOpen}')
    expect(workout).toContain('aria-controls={workoutNoteContentId}')
    expect(workout).toContain('hidden={!workoutNoteOpen}')
    expect(workout).toContain("<Icon name={workoutNoteOpen ? 'chevronUp' : 'chevronDown'} />")
    expect(workout).toContain("const workoutNoteId = 'workout-note-' + sid")
  })

  it('renders all exercises without bottom session navigation', () => {
    const css = source('index.css')
    const workout = source('views/Workout.jsx')
    expect(workout).not.toContain('workout-session-nav')
    expect(workout).not.toContain('<select')
    expect(workout).not.toContain('session-selector')
    expect(workout).not.toContain('session-index')
    expect(css).not.toContain('.workout-session .session-index')
    expect(css).not.toContain('.session-selector')
    expect(css).toContain('.workout-session-nav > button{flex:1 1 0;width:auto}')
  })

  it('guards unlocked dismissal while preserving locked dialogs', () => {
    const modal = source('components/Modals.jsx')
    expect(modal).toContain("e.key === 'Escape' && !sheet.locked")
    expect(modal).toContain("!sheet.locked && <button type=\"button\" className=\"iconbtn modal-close\"")
    expect(modal).toContain('returnFocus.current.focus()')
  })

  it('uses native buttons for the audited Home and scheduling actions', () => {
    const home = source('views/Home.jsx')
    const sheets = source('sheets.jsx')
    expect(home).toContain('<button type="button" key={i} className={\'wday\'')
    expect(home).toContain('<button type="button" className="today-row"')
    expect(home).toContain('className="card tappable interactive-card"')
    expect(sheets).toContain('<button type="button" key={r.id} className="item"')
    expect(sheets).toContain("className=\"item\" onClick={() => set('rest')}")
  })

  it('keeps selective export dates accessible and limited to trained days', () => {
    const home = source('views/Home.jsx')
    const sheets = source('sheets.jsx')
    expect(home).toContain("onClick={() => workoutExportSheet()}")
    expect(home).toContain("aria-label={t('Export')}")
    expect(sheets).toContain('disabled={!available} aria-pressed={on}')
    expect(sheets).toContain("aria-label={t(on ? 'Deselect {0}' : 'Select {0}'")
    expect(sheets).toContain('disabled={!selected.size || busy}')
    expect(sheets).toContain('createWorkoutBackup(st, selected)')
  })

  it('announces the single mobile toast without changing its store behavior', () => {
    const toast = source('components/Toast.jsx')
    const css = source('index.css')
    expect(toast).toContain('role="status" aria-live="polite"')
    expect(css).toContain('max-width:calc(100vw - 2 * var(--pad))')
    expect(css).toContain('overflow-wrap:anywhere')
  })

  it('keeps workout grids aligned and editable at narrow widths', () => {
    const css = source('index.css')
    const ui = source('components/ui.jsx')
    const workout = source('views/Workout.jsx')
    expect(css).toContain('--set-grid-template')
    expect(css).toContain('minmax(104px,1.35fr)')
    expect(css).toContain('.setgrid-scroll')
    expect(css).toContain('overflow-x:auto')
    expect(css).toContain('.setrow.per-side,.sethead.per-side')
    expect(css).toContain('.setrow.per-side > .side-checks{grid-column:8;')
    expect(css).toContain('.setrow:not(.per-side) > .setinfo{grid-column:var(--set-info-col);justify-self:center}')
    expect(css).toContain('.setrow:not(.per-side) > .chk{grid-column:var(--set-check-col);justify-self:center}')
    expect(css).toContain('.sethead.no-col2.timed,.setrow.no-col2.timed')
    expect(css).toContain('--set-go-col:3;--set-check-col:4')
    expect(css).not.toContain('min-width:340px')
    expect(css).not.toContain('min-width:386px')
    expect(css).toContain('@media (max-width:430px)')
    expect(css).toContain('minmax(70px,1.2fr) minmax(54px,1fr) minmax(58px,.85fr) 44px 44px')
    expect(css).toContain('scroll-margin-top')
    expect(workout).toContain('className="setgrid-scroll"')
    expect(workout).toContain('className="side-sp"')
    expect(workout).toContain('aria-live="polite"')
    expect(ui).toContain('parseNumberDraft')
    expect(ui).toContain('if (!result.valid) return')
    expect(ui).toContain('setDraft(raw)')
    expect(ui).toContain('nullable ? null : 0')
  })

  it('contains long shared selector labels and values without losing row affordances', () => {
    const css = source('index.css')
    const ui = source('components/ui.jsx')
    const stats = source('views/Stats.jsx')
    const routine = source('views/RoutineEdit.jsx')
    const sheets = source('sheets.jsx')
    expect(css).toContain('overflow:hidden;text-overflow:ellipsis;white-space:nowrap')
    expect(css).toContain('min-width:0;max-width:50%;')
    expect(ui).toContain('{subtitle && <span className="lrow-s">{subtitle}</span>}')
    expect(ui).toContain("accessory === 'chevron'")
    expect(stats).toContain("<SelectRow title={t('Exercise')}")
    expect(routine).toContain("<SelectRow icon=\"chartLine\" title={t('Progression')}")
    expect(sheets).toContain("<SelectRow title={t('Rule')")
    expect(sheets).toContain("t('Follow the routine ({0})',")
  })

  it('keeps landmarks, focus, targets, and overlay clearance explicit', () => {
    const css = source('index.css')
    const workout = source('views/Workout.jsx')
    expect(workout).toContain('<main')
    expect(workout).toContain('aria-labelledby={\'session-heading-\' + entry.sid}')
    expect(workout).toContain("aria-label={t('Move up')}")
    expect(workout).toContain("aria-label={t('Move down')}")
    expect(css).toContain('.workout-session .wprog{position:sticky')
    expect(css).toContain('bottom:calc(96px + var(--sab))')
    expect(css).toContain('calc(180px + var(--sab))')
    expect(css).toContain('@media (prefers-reduced-motion: reduce)')
    expect(css).toContain('min-width:44px;min-height:44px')
  })

  it('keeps localized controls and non-runtime evidence contracts explicit', () => {
    const workout = source('views/Workout.jsx')
    const spanish = source('locales/es.js')
    const fallbackLocale = source('locales/de.js')
    expect(workout).toContain("t('Move up')")
    expect(workout).toContain("t('Move down')")
    expect(workout).toContain("t('Discard')")
    expect(spanish).toContain("'Move up'")
    expect(fallbackLocale).toContain("'Move up'")
    expect(source('index.css')).toContain('@media (prefers-reduced-motion: reduce)')
    expect(workout).not.toContain('navigator.userAgent')
  })

  it('keeps passkey diagnostics in the console and localizes user-facing failures', () => {
    const settings = source('views/Settings.jsx')
    expect(settings).toContain("console.error('Passkey sign-in failed:', e)")
    expect(settings).toContain("toast(t('Sign-in failed'))")
    expect(settings).not.toContain("toast(e.message || t('Sign-in failed'))")
  })
})
